source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "jekyll-archives"
gem "jekyll-diagrams"
gem "jekyll-email-protect"
gem "jekyll-feed"
gem "jekyll-get-json"
gem "jekyll-imagemagick"
gem "jekyll-jupyter-notebook"
gem "jekyll-link-attributes"
gem "jekyll-minifier"
gem "jekyll-paginate-v2"
gem "jekyll-scholar"
gem "jekyll-sitemap"
gem "jekyll-socials"
gem "jekyll-tabs"
gem "jekyll-toc"
gem "jekyll-twitter-plugin"
gem "jemoji"
gem "kramdown-parser-gfm"
gem "webrick", "~> 1.8"
gem "feedjira"
gem "httparty"
